/**
 * Vibe Coding Projects ✨
 * No-code / describe-to-code playgrounds and builders
 */

export const vibeCodingProjects = [
  {
    name: "EasyGen - AI Diagram Generator ✨",
    url: "https://easygenme.netlify.app/",
    description: "Modern open-source web application that transforms text descriptions into professional diagrams using AI. Built with React, TypeScript, and Mermaid.js. Features real-time preview, multiple export formats (SVG, PNG, PDF), shareable links, intuitive split-panel editor, and support for various diagram types including flowcharts, sequence diagrams, class diagrams, state diagrams, ER diagrams, timelines, and Gantt charts.",
    author: "@ellweb3",
    submissionDate: "2025-08-11",
    order: 1
  },
  {
    name: "Visiora - Image Generation using AI 🎨",
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 3,
    stars: 2,
    stars: 2,
    stars: 2,
    stars: 2,
    stars: 2,
    stars: 2,
    stars: 2,
    stars: 2,
    stars: 2,
    stars: 2,
    stars: 2,
    stars: 2,
    stars: 2,
    stars: 2,
    url: "https://visiora-img.netlify.app/",
    description: "A modern web application that transforms text prompts into stunning AI-generated images. Built with React and powered by Pollinations AI, it features multiple AI models (Flux, Turbo, Kontext), flexible image dimensions, seed control for reproducible results, and a responsive design that works seamlessly across all devices.",
    author: "@Kandariarjun07",
    repo: "https://github.com/Kandariarjun07/Visiora",
    stars: 0,
    submissionDate: "2025-08-05",
    order: 1
  },
  {
    name: "PairFusion",
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    stars: 5,
    url: "https://pair-fusion.vercel.app/",
    description: "A real-time AI powered, scalable and feature-rich collaborative IDE built for modern development teams. Experience seamless pair programming, instant feedback, and a professional-grade toolset designed for maximum productivity.",
    author: "@auraticabhi",
    repo: "https://github.com/auraticabhi/PairFusion",
    stars: 0,
    submissionDate: "2025-07-03",
    order: 1
  },
  {
    name: "CraftUI",
    url: "https://craftui.studio/",
    description: "An AI-powered tool that simplifies UI design by turning text prompts or images into clean, production-ready components. It supports real-time customization with theme switching, framework selection (like Tailwind or Bootstrap), and intuitive editing. Whether you're a developer or designer, CraftUI helps you design faster, smarter, and with ease. Explore, remix, and share your creations in a growing creative community.",
    author: "@imhardikdesai",
    submissionDate: "2025-06-19",
    order: 1
  },
  {
    name: "AI Code Generator",
    url: "https://codegen.on.websim.com/",
    description: "A websim project that generates code from description, selected programming language and other options. Integrates Pollinations because it allows for more models to choose from for potentially better results. It has modes like: Code Generator, Code Explainer, Reviewer, etc.",
    author: "@Miencraft2",
    submissionDate: "2025-05-25",
    order: 1
  },
  {
    name: "VibeCoder",
    description: "A conversational coding environment that lets you create applications by describing them in natural language.",
    author: "@Aashir__Shaikh",
    authorUrl: "https://x.com/Aashir__Shaikh",
    submissionDate: "2025-03-25",
    order: 1
  },
  {
    name: "Pollinations Task Master",
    stars: 24,
    stars: 24,
    stars: 24,
    stars: 24,
    stars: 24,
    stars: 24,
    stars: 24,
    stars: 24,
    stars: 24,
    stars: 23,
    stars: 23,
    stars: 23,
    stars: 23,
    stars: 23,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 22,
    stars: 21,
    stars: 20,
    url: "https://github.com/LousyBook94/pollinations-task-master",
    description: "A task management system that uses AI to help break down and organize development tasks through natural language interaction.",
    author: "@LousyBook94",
    repo: "https://github.com/LousyBook94/pollinations-task-master",
    submissionDate: "2025-05-12",
    stars: 20,
    order: 1
  },
  {
    name: "Qwen-Agent",
    stars: 12463,
    stars: 12451,
    stars: 12437,
    stars: 12419,
    stars: 12406,
    stars: 12390,
    stars: 12378,
    stars: 12369,
    stars: 12356,
    stars: 12342,
    stars: 12332,
    stars: 12314,
    stars: 12303,
    stars: 12283,
    stars: 12261,
    stars: 12246,
    stars: 12221,
    stars: 12209,
    stars: 12202,
    stars: 12188,
    stars: 12177,
    stars: 12171,
    stars: 12148,
    stars: 12126,
    stars: 12104,
    stars: 12080,
    stars: 12076,
    stars: 12061,
    stars: 12043,
    stars: 12007,
    stars: 11996,
    stars: 11977,
    stars: 11944,
    stars: 11922,
    stars: 11892,
    stars: 11803,
    url: "https://github.com/QwenLM/Qwen-Agent",
    description: "A framework for developing agentic LLM applications.",
    repo: "https://github.com/QwenLM/Qwen-Agent",
    stars: 11523,
    order: 1
  },
  {
    name: "JCode Website Builder",
    url: "https://jcode-ai-website-bulder.netlify.app/",
    description: "A website generator using Pollinations text API.",
    author: "@rtxpower",
    order: 1
  },
  {
    name: "Pollinations.DIY",
    url: "https://pollinations.diy",
    description: "A browser-based coding environment based on bolt.diy, featuring integrated Pollinations AI services, visual code editing, and project management tools.",
    author: "@thomash",
    submissionDate: "2025-03-01",
    order: 1
  },
  {
    name: "Websim",
    url: "https://websim.ai/c/bXsmNE96e3op5rtUS",
    description: "A web simulation tool that integrates Pollinations.ai.",
    author: "@thomash",
    order: 2
  },
  {
    name: "NetSim",
    url: "https://netsim.us.to/",
    description: "websim.ai clone that's actually good",
    author: "@kennet678",
    submissionDate: "2025-04-15",
    order: 1
  },
  {
    name: "Pollin-Coder",
    url: "https://pollin-coder.megavault.in",
    description: "A free AI-powered website builder that lets anyone create a clean site just by describing it. It uses Pollinations AI to generate the content and layout instantly.",
    author: "@r3ap3redit",
    submissionDate: "2025-05-19",
    order: 1
  },
  {
    name: "JustBuildThings",
    url: "https://justbuildthings.com",
    description: "A natural language programming interface that lets users create web applications by simply describing what they want to build, using Pollinations AI to generate code and assets.",
    author: "@buildmaster",
    submissionDate: "2025-05-02",
    order: 1
  },
  {
    name: "SocialScribe",
    stars: 7,
    stars: 7,
    stars: 7,
    stars: 7,
    stars: 7,
    stars: 7,
    stars: 7,
    stars: 7,
    stars: 7,
    stars: 7,
    stars: 7,
    stars: 7,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 6,
    stars: 5,
    url: "https://socialscribe.pages.dev/",
    description: "An AI-powered Chrome extension that fixes grammar, rewrites text, and enhances your writing across websites like Twitter, LinkedIn, and Gmail, with customizable tone, length, and platform-specific formatting, plus support for emojis, hashtags, and keyword suggestions.",
    author: "@sh20raj",
    repo: "https://github.com/sh20raj/socialscribe",
    stars: 1,
    submissionDate: "2025-07-13",
    order: 1
  },
  {
    name: "Berrry Computer",
    url: "https://berrry.app",
    description: "Make tiny self-contained web apps with AI. Find a tweet with an interesting app idea, mention @BerrryComputer in a reply, and get back an app on a unique subdomain. Uses pollinations.ai to create dynamic AI experiences in generated apps.",
    author: "@vgrichina",
    authorUrl: "https://github.com/vgrichina",
    repo: "https://github.com/Strawberry-Computer",
    submissionDate: "2025-07-16",
    order: 0
  },
  {
    name: "websim-pollinations-ai",
    stars: 3260,
    stars: 3255,
    stars: 3249,
    stars: 3245,
    stars: 3238,
    stars: 3231,
    stars: 3227,
    stars: 3223,
    stars: 3216,
    stars: 3202,
    stars: 3198,
    stars: 3194,
    stars: 3191,
    stars: 3185,
    stars: 3179,
    stars: 3171,
    stars: 3161,
    stars: 3151,
    stars: 3151,
    stars: 3145,
    stars: 3136,
    stars: 3132,
    stars: 3124,
    stars: 3119,
    stars: 3114,
    stars: 3099,
    stars: 3093,
    stars: 3091,
    stars: 3082,
    stars: 3067,
    stars: 3057,
    stars: 3044,
    stars: 3031,
    stars: 3026,
    stars: 3017,
    stars: 3016,
    stars: 2956,
    url: "https://websim.pollinations.ai",
    description: "A lightweight websim for creating web simulations with AI. Usage: https://websim.pollinations.ai/[prompt] - Simply append your prompt to the URL to generate interactive web experiences.",
    author: "@thomash",
    repo: "https://github.com/pollinations/pollinations/tree/master/websim.pollinations.ai",
    submissionDate: "2025-08-03",
    order: 0.5
  }
];
